# Generated by Django 2.2 on 2022-03-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('health', models.CharField(blank=True, max_length=255, null=True)),
                ('flammability', models.CharField(blank=True, max_length=255, null=True)),
                ('specificity', models.CharField(blank=True, max_length=255, null=True)),
                ('instability', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
